

GET http://localhost:9000/payment
###

DELETE http://localhost:9000/payment/

###
POST http://localhost:9000/payment HTTP/1.1
content-type: application/json

{
    "reference": "Voke Olomu",
    "message": "superadmin",
    "name": "password1",
    "email": "vokeolomu5@email.com",
    "amount": "090928888833",
   
}

###
POST http://localhost:9000/client HTTP/1.1
content-type: application/json

{
    "fullName": "Voke Olomu",
    "role": "superadmin",
    "password": "password1",
    "email": "volomu@ithorizonsng.com",
    "phone": "090928888833",
    "isVerified": true,
    "isCreated": false,
    "isEnabled": true,
    "isAdmin": true
}
###

GET http://localhost:9000/client HTTP/1.1
content-type: application/json
